spn_credentials:
    tenant_id: 441d4a8f-7999-4d6a-9670-672cf8d03e35           #The tenant id

deploy_options:
    max_file_size_supported_in_mb: 101                        #Maximum File Size Supported. Action only supports files upto 1000 MB.
    
pbix_deploy_options:
    pbix_name_conflict: CreateOrOverwrite                     #Determines what to do if a dataset with the same name already exists. Abort, CreateOrOverwrite, GenerateUniqueName, Ignore, Overwrite (https://docs.microsoft.com/en-us/rest/api/power-bi/imports/post-import-in-group#post-import-example)
    override_model_name: True                                 #Determines whether to override existing label on model during republish of PBIX file, service default value is true.
    override_report_label: True                               #Determines whether to override existing label on report during republish of PBIX file, service default value is true.

rdl_deploy_options:
    max_file_size_supported_in_mb: 101                        #Maximum File Size Supported. Action only supports files upto 1000 MB.
    rdl_name_conflict: Overwrite                              #Determines what to do if a dataset with the same name already exists. Only Abort and Overwrite are supported with Rdl files. (https://docs.microsoft.com/en-us/rest/api/power-bi/imports/post-import-in-group#post-import-example)

deploy_location:
    workspace_id: c4dde448-b154-4d86-9704-d02f47778959        #The workspace ID